name: ultimon-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - pydantic==2.5.0
    - pydantic-settings==2.1.0
    - websockets==12.0
    - python-multipart==0.0.6
    - aiofiles==23.2.1
    - python-dotenv==1.0.0
    - aiohttp==3.9.1
    - pythonnet==3.0.3
    - HardwareMonitor==1.0.0
