declare const $state: <T>(initial: T) => T;
declare const $derived: <T>(computation: () => T) => T;
declare const $effect: (callback: () => void) => void;
declare const $props: <T>() => T;
declare const $inspect: <T>(value: T) => T;
declare const $host: <T>(value: T) => T;
declare const $template: <T>(value: T) => T;
declare const $component: <T>(value: T) => T;
declare const $render: <T>(value: T) => T;
declare const $cleanup: (callback: () => void) => void;
declare const $on: <T>(event: string, callback: (event: T) => void) => void;
declare const $onMount: (callback: () => void) => void;
declare const $onDestroy: (callback: () => void) => void;
declare const $onError: (callback: (error: Error) => void) => void;
declare const $onInvalidate: (callback: () => void) => void;
declare const $onUpdate: (callback: () => void) => void;
declare const $onBeforeUpdate: (callback: () => void) => void;
declare const $onAfterUpdate: (callback: () => void) => void;
declare const $onBeforeMount: (callback: () => void) => void;
declare const $onAfterMount: (callback: () => void) => void;
declare const $onBeforeDestroy: (callback: () => void) => void;
declare const $onAfterDestroy: (callback: () => void) => void;
declare const $onBeforeRender: (callback: () => void) => void;
declare const $onAfterRender: (callback: () => void) => void;
declare const $onBeforeUpdate: (callback: () => void) => void;
declare const $onAfterUpdate: (callback: () => void) => void;
declare const $onBeforeMount: (callback: () => void) => void;
declare const $onAfterMount: (callback: () => void) => void;
declare const $onBeforeDestroy: (callback: () => void) => void;
declare const $onAfterDestroy: (callback: () => void) => void;
declare const $onBeforeRender: (callback: () => void) => void;
declare const $onAfterRender: (callback: () => void) => void;
